sudo: false
language: python
python:
  - "3.4"
  - "2.7"
install: 
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - pip install -rrequirements.txt
  - python setup.py install
script: python setup.py test

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - libasound2-dev 
      - libboost-dev 
